cluster_features = [
    'duration_sess',
    'pre_clickout_steps',
    'time_per_step',
    'count_total_int_sess',
    'count_clickouts_sess',
    'count_rating_actions_sess',
    'count_info_actions_sess',
    'count_image_actions_sess',
    'count_deals_actions_sess',
    'count_searches_sess',
    'dwell_time_mean_int_sess',
    'dwell_time_mean_co_sess',
    'unique_int_items_sess',
    'unique_co_items_sess',
    'unique_co_ratio',
    'unique_int_ratio',
    'unique_city_sess',
    'count_items_above_2_co_sess',
    'count_items_above_2_int_sess',
    'count_items_above_3_int_sess',
    'count_items_above_5_int_sess'
 ]


lgb_features = [
#  'city',
#  'country',
#  'platform',
#  'device',
 'len_impressions',
 'len_prices',
 'item_price',
 'item_position',
 'price_rank',
 'item_int_count_sess',
 'item_image_int_count_sess',
 'item_co_count_sess',
 'item_search_count_sess',
 'item_rating_int_count_sess',
 'item_deals_int_count_sess',
 'item_mean_dwell_time_sess',
 'item_max_dwell_time_sess',
 'item_sum_dwell_time_sess',
 'item_mean_dwell_time_image_sess',
 'item_max_dwell_time_image_sess',
 'item_sum_dwell_time_image_sess',
 'item_mean_dwell_time_co_sess',
 'item_max_dwell_time_co_sess',
 'item_sum_dwell_time_co_sess',
 'step_item_last_int',
 'dwell_time_item_last_int',
 'order_item_last_int',
 'step_item_last_co',
 'dwell_time_item_last_co',
 'order_item_last_co',
 'step_item_last_image',
 'dwell_time_item_last_image',
 'order_item_last_image',
 'duration_sess',
 'pre_clickout_steps',
 'time_per_step',
 'count_total_int_sess',
 'count_clickouts_sess',
 'count_rating_actions_sess',
 'count_info_actions_sess',
 'count_image_actions_sess',
 'count_deals_actions_sess',
 'count_searches_sess',
 'count_price_action',
 'count_distance_action',
 'count_rating_action',
 'item_position_mean_int_sess',
 'item_position_max_int_sess',
 'session_price_mean_int_sess',
 'session_price_max_int_sess',
 'price_rank_mean_int_sess',
 'price_rank_max_int_sess',
 'dwell_time_mean_int_sess',
 'dwell_time_max_int_sess',
 'item_position_mean_co_sess',
 'item_position_max_co_sess',
 'session_price_mean_co_sess',
 'session_price_max_co_sess',
 'price_rank_mean_co_sess',
 'price_rank_max_co_sess',
 'dwell_time_mean_co_sess',
 'dwell_time_max_co_sess',
 'unique_int_items_sess',
 'unique_co_items_sess',
 'unique_co_ratio',
 'unique_int_ratio',
 'unique_city_sess',
 'imp_price_mean_sess',
 'imp_price_max_sess',
 'step_last_int_sess',
 'action_type_last_int_sess',
 'item_position_last_int_sess',
 'session_price_last_int_sess',
 'price_rank_last_int_sess',
 'dwell_time_last_int_sess',
 'step_last_co_sess',
 'item_position_last_co_sess',
 'session_price_last_co_sess',
 'price_rank_last_co_sess',
 'dwell_time_last_co_sess',
 'dwell_time_last_int_item',
 'dwell_time_last_co_item',
 'step_last_imp_sess',
 'time_last_pre_int_to_co',
 'time_last_pre_co_to_co',
 'item_price_pos_one_sess',
 'price_rank_pos_one_sess',
 'dwell_time_pos_one_sess',
 'last_2_ints_pos_diff',
 'count_items_above_2_co_sess',
 'count_items_above_2_int_sess',
 'cluster_sess',
 'item_pos_over_sess_pos',
 'item_pos_over_sess_pos_max',
 'item_price_over_sess_price',
 'item_price_over_sess_price_max',
 'item_pr_over_sess_pr',
 'item_pr_over_sess_pr_max',
 'item_dt_over_sess_dt',
 'item_dt_over_sess_dt_max',
 'item_pos_over_co_pos',
 'item_pos_over_co_pos_max',
 'item_price_over_co_price',
 'item_price_over_co_price_max',
 'item_pr_over_co_pr',
 'item_pr_over_co_pr_max',
 'item_dt_over_co_dt',
 'item_dt_over_co_dt_max',
 'item_price_over_imp_price',
 'item_price_over_imp_price_max',
 'is_last_interacted',
#  'is_last_clicked',
 'item_price_over_last_int_sess',
 'item_pos_over_last_int_sess',
 'item_pr_over_last_int_sess',
 'item_last_int_dt_over_last_int_sess',
 'item_total_dt_over_last_int_sess',
 'item_price_over_last_co_sess',
 'item_pos_over_last_co_sess',
 'item_pr_over_last_co_sess',
 'item_last_co_dt_over_last_co_sess',
 'item_total_dt_over_last_co_sess',
 'item_price_over_pos_one_sess',
 'item_pr_over_pos_one_sess',
 'item_dt_over_pos_one_sess',
 'item_last_int_step_recency',
 'item_last_co_step_recency',
 'item_last_image_step_recency',
 'item_last_int_ts_recency',
 'item_last_co_ts_recency',
 'item_last_image_ts_recency',
 'num_co_since_item_last_co',
 'num_int_since_item_last_int',
 'num_img_since_item_last_image',
 'ctr_sess',
 'count_global_img_int',
 'count_global_rating_int',
 'count_global_search',
 'count_global_info_int',
 'count_global_deals_int',
 'count_global_co',
 'count_global_int',
 'count_global_imp',
 'ctr',
 'co_per_int',
 'co_per_img_int',
 'co_per_search',
 'co_per_rating_int',
 'co_per_deals_int',
 'co_prob_int',
 'co_prob_img',
 'co_prob_search',
 'co_prob_rating',
 'co_prob_deals',
 'co_prob_int_by_dt',
 'co_prob_img_by_dt',
 'expected_clicks',
 'position_ctr',
 'pos_adjusted_ctr',
 'co_count_over_expected',
 'sess_num_int',
 'sess_num_co',
 'sess_num_img',
 'co_prob_in_sess_int',
 'co_prob_in_sess_img',
 'co_prob_in_sess_int_by_dt',
 'co_prob_in_sess_img_by_dt',
 'position_rel',
 'price_rank_rel',
 'position_global_abs',
 'position_global_rel',
 'price_rank_global_abs',
 'price_rank_global_rel',
 'position_abs_diff',
 'position_abs_ratio',
 'position_rel_diff',
 'position_rel_ratio',
 'price_rank_abs_diff',
 'price_rank_abs_ratio',
 'price_rank_rel_diff',
 'price_rank_rel_ratio',
 'item_num_prop',
#  'business',
#  'swimming',
#  'family',
 'activities',
 'wellness',
#  'beach',
#  'wifi',
#  'airport',
 'facilities_and_services',
#  'is_luxury',
#  'is_resort',
#  'is_hotel',
#  'is_motel',
#  'is_hostel',
#  'is_house',
#  'is_svc_apt',
#  'hotel_style',
#  'dining_options',
 'star_level',
 'rating_level',
#  'mean_price_co_city',
#  'item_price_over_mean_co_city',
#  'mean_price_co_city_platfrom',
#  'item_price_over_mean_co_city_platfrom',
#  'mean_price_co_country',
#  'item_price_over_mean_co_country',
#  'mean_price_co_city_star',
#  'item_price_over_mean_co_city_star',
 'mean_price_imp_city',
 'max_price_imp_city',
 'item_price_over_mean_imp_city',
 'item_price_over_max_imp_city',
 'mean_price_imp_country',
 'max_price_imp_country',
 'item_price_over_mean_imp_country',
 'item_price_over_max_imp_country',
 'mean_price_imp_star_level',
 'max_price_imp_star_level',
 'item_price_over_mean_imp_star_level',
 'item_price_over_max_imp_star_level',
 'mean_price_imp_rating_level',
 'max_price_imp_rating_level',
 'item_price_over_mean_imp_rating_level',
 'item_price_over_max_imp_rating_level',
#  'mean_price_int_city',
#  'item_price_over_mean_int_city',
#  'mean_price_int_city_platform',
#  'item_price_over_mean_int_city_platform',
#  'mean_price_int_country',
#  'item_price_over_mean_int_country',
#  'mean_price_int_star',
#  'item_price_over_mean_int_star',
#  'mean_price_int_rating',
#  'item_price_over_mean_int_rating'
]

