combined_meta_cols = {
    'business': ['Business Hotel',
                 'Business Centre',
                 'Conference Rooms',
                 'Convention Hotel'],
    'swimming': ['Swimming Pool (Bar)',
                 'Swimming Pool (Combined Filter)',
                 'Swimming Pool (Indoor)',
                 'Swimming Pool (Outdoor)'],
    'family': ['Family Friendly',
               'Cot',
               "Kids' Club",
               'Childcare'],
    'activities': ['Ski Resort',
                   'Skiing',
                   'Hiking Trail',
                   'Horse Riding',
                   'Minigolf',
                   'Organised Activities',
                   'Pool Table',
                   'Playground',
                   'Golf Course',
                   'Farmstay',
                   'Casa Rural (ES)',
                   'Shooting Sports',
                   'Sailing',
                   'Diving',
                   'Surfing',
                   'Table Tennis',
                   'Volleyball',
                   'Bike Rental',
                   'Boat Rental',
                   'Casino (Hotel)',
                   'Tennis Court',
                   'Tennis Court (Indoor)',
                   'Water Slide',
                   'Nightclub',
                   'Camping Site',
                   'Bowling'],
    'wellness': ['Spa Hotel',
                 'Spa (Wellness Facility)',
                 'Steam Room',
                 'Sauna',
                 'Massage',
                 'Jacuzzi (Hotel)',
                 'Hydrotherapy',
                 'Health Retreat',
                 'Body Treatments',
                 'Hot Stone Massage',
                 'Solarium',
                 'Gym',
                 'Fitness',
                 'Beauty Salon'],
    'beach': ['Sun Umbrellas',
              'Beach',
              'Beach Bar',
              'Direct beach access'],
    'wifi': ['Free WiFi (Combined)',
             'Free WiFi (Public Areas)',
             'Free WiFi (Rooms)',
             'WiFi (Public Areas)',
             'WiFi (Rooms)',
             'Computer with Internet'],
    'airport': ['Airport Hotel', 'Airport Shuttle'],
    'facilities_and_services': ['Air Conditioning',
                                'Central Heating',
                                'Fan',
                                'Wheelchair Accessible',
                                'Washing Machine',
                                'Towels',
                                'Terrace (Hotel)',
                                'Television',
                                'Teleprinter',
                                'Telephone',
                                'Szep Kartya',
                                'Sitting Area (Rooms)',
                                'Shower',
                                'Self Catering',
                                'Satellite TV',
                                'Safe (Rooms)',
                                'Safe (Hotel)',
                                'Radio',
                                'Porter',
                                'Openable Windows',
                                'Lift',
                                'Laundry Service',
                                'Ironing Board',
                                'Hypoallergenic Rooms',
                                'Hypoallergenic Bedding',
                                'On-Site Boutique Shopping',
                                'Non-Smoking Rooms',
                                'Hammam',
                                'Hairdryer',
                                'Hairdresser',
                                'Fridge',
                                'Flatscreen TV',
                                'Express Check-In / Check-Out',
                                'Electric Kettle',
                                'Doctor On-Site',
                                'Desk',
                                'Deck Chairs',
                                'Cosmetic Mirror',
                                'Convenience Store',
                                'Concierge',
                                'Car Park',
                                'Cable TV',
                                'Bungalows',
                                'Bathtub',
                                'Balcony',
                                'Accessible Parking',
                                'Accessible Hotel',
                                'Microwave',
                                'Pet Friendly',
                                'Gay-friendly',
                                'Large Groups',
                                'Senior Travellers',
                                'Singles',
                                'Honeymoon',
                                'All Inclusive (Upon Inquiry)',
                                'Romantic',
                                'Adults Only',
                                'Bed & Breakfast'],
    'is_luxury': ['Luxury Hotel'],
    'is_resort': ['Resort'],
    'is_hotel': ['Hotel'],
    'is_motel': ['Motel'],
    'is_hostel': ['Hostel', 'Hostal (ES)'],
    'is_house': ['House / Apartment'],
    'is_svc_apt': ['Serviced Apartment'],
    'hotel_style': ['Boutique Hotel',
                    'Club Hotel',
                    'Country Hotel',
                    'Design Hotel',
                    'Eco-Friendly hotel',
                    'Theme Hotel'],
    'dining_options': ['Room Service',
                       'Room Service (24/7)',
                       'Restaurant',
                       'Reception (24/7)',
                       'Kosher Food',
                       'Hotel Bar',
                       'Halal Food']
    }